language: android
android:
        components:
                - tools
                - tools
                - platform-tools
                - build-tools-27.0.3
                - android-27
                - extra-android-support
                - extra-android-m2repository
before_install:
        - yes | sdkmanager "platforms;android-27"
script:
   - ./gradlew build connectedCheck
branches:
        only:
                - master
